#!/usr/bin/env python3
# 45-entry OPP table generator per OC variant. Usage: gen_opp.py 1500 > opp_table.h
# Rules (from the 390-1100 stock table, 700-1100 slope is a steady ~2000/50MHz):
# - Vraw(F) = 93750 + (F-1200)/50*2000, 2000/50MHz staircase down to 1100
# - argv[2] optional: V0 override (peak volt, uV) for UV/OV step tests
# - all volts snapped to the 625 PMIC grid (round-half-up)
# - below 1100: live-UV tail (boot result + AVS/aging, -1250), proven
# - vsram = volt ; posdiv 1 ; margin 1875 ; power=0 (computed by the module)
import sys

V0_ANCHOR, V0_SLOPE = 93750, 2000
F_STEP, V_STEP, PMIC_GRID = 50000, 2000, 625
F_MERGE = 1100000

# tail idx3..44: freq, volt, vsram, posdiv, margin (live-UV, from unit, OK)
TAIL = [
 (1058000,75000,76250,1,1875),(1045000,74375,75625,1,1875),
 (1031000,73750,75000,1,1875),(1017000,73125,75000,1,1875),
 (1003000,72500,75000,1,1875),(990000,71875,75000,1,1875),
 (976000,71250,75000,1,1875),(962000,71250,75000,1,1875),
 (948000,70625,75000,2,1875),(935000,70000,75000,2,1875),
 (921000,69375,75000,2,1875),(907000,68750,75000,2,1875),
 (893000,68125,75000,2,1875),(880000,67500,75000,2,1875),
 (868000,66875,75000,2,1875),(857000,66875,75000,2,1875),
 (846000,66250,75000,2,1875),(835000,65625,75000,2,1250),
 (823000,65000,75000,2,1250),(812000,65000,75000,2,1250),
 (801000,64375,75000,2,1250),(790000,63750,75000,2,1250),
 (778000,63750,75000,2,1250),(767000,63125,75000,2,1250),
 (756000,62500,75000,2,1250),(745000,61875,75000,2,1250),
 (733000,61875,75000,2,1250),(722000,61250,75000,2,1250),
 (711000,60625,75000,2,1250),(700000,60000,75000,2,1250),
 (674000,60000,75000,2,1250),(648000,59375,75000,2,1250),
 (622000,59375,75000,2,1250),(596000,58750,75000,2,625),
 (570000,58750,75000,2,625),(545000,58125,75000,2,625),
 (519000,58125,75000,2,625),(493000,57500,75000,2,625),
 (467000,57500,75000,2,625),(441000,56875,75000,2,625),
 (415000,56875,75000,2,625),(390000,56250,75000,2,625),
]

def snap(v):
    return (v + PMIC_GRID // 2) // PMIC_GRID * PMIC_GRID

def main():
    fmax = int(sys.argv[1]) * 1000
    assert 1200000 <= fmax <= 1800000 and fmax % 50000 == 0, "variants 1200-1800 step 50"
    raw0 = V0_ANCHOR + (fmax - 1200000) // 50000 * V0_SLOPE
    if len(sys.argv) > 2:  # UV/OV step: shift the staircase anchor to the V0 override
        raw0 = snap(int(sys.argv[2]))
    v0 = snap(raw0)
    head = []
    i = 0
    f = fmax
    while f >= F_MERGE:
        v = snap(raw0 - V_STEP * i)
        head.append((f, v, v, 1, 1875))
        f -= F_STEP
        i += 1
    tbl = head + TAIL[len(head) - 3:]
    assert len(tbl) == 45, f"entry count {len(tbl)} != 45"
    # guard = largest step in the table + 5000 slack (live tail can drift with AVS
    # from the TAIL snapshot; the module validates the live-merged result, not the snapshot)
    maxstep = max(abs(tbl[i][1] - tbl[i - 1][1]) for i in range(1, len(tbl)))
    V_GUARD = maxstep + 5000
    for i, (f, v, s, p, m) in enumerate(tbl):
        assert 187500 <= f <= 1900000, f"freq idx{i} {f}"
        assert 50000 <= v <= 129300, f"volt idx{i} {v}"
        assert 75000 <= s <= 129300, f"vsram idx{i} {s}"
        if i:
            pf, pv = tbl[i-1][0], tbl[i-1][1]
            assert f < pf, f"freq idx{i} not descending"
            assert abs(v - pv) <= V_GUARD, f"volt step idx{i} {abs(v-pv)}"
    print(f"// generated by gen_opp.py, OC variant {fmax//1000}MHz @{v0}uV "
          f"+ staircase down to 1100, live-UV tail. power=0 (computed by module).")
    print(f"#define HEAD_NUM {len(head)}")
    print(f"#define HEAD_VGUARD {V_GUARD}")
    print("static struct opp opp_new[OPP_NUM] = {")
    for f, v, s, p, m in tbl:
        print(f"  {{{f},{v},{s},{p},{m},0}},")
    print("};")
    print(f"// idx0 {fmax} {v0} | entries {len(tbl)} | OK",
          file=sys.stderr)

main()
