#!/usr/bin/env python3
# 45-entry OPP table generator per OC variant. Usage: gen_opp.py 1700 > opp_table.h
# Volt model (anchored at stock: 1100MHz @ 0.75V):
# - V(F) = snap625(round(F_MHz * 0.682) * 100), same ratio for the whole head
# - argv[2] optional: V0 override (peak volt, uV); applied as a flat delta to
#   the whole head so UV/OV step tests keep the curve shape
# - all volts snapped to the 625 PMIC grid (round-half-up)
# - below 1100: live-UV tail (boot result + AVS/aging, -1250), proven
# - vsram = volt ; posdiv 1 ; margin 1875 ; power=0 (computed by the module)
# Driver ceilings (from mtk_gpufreq_mt6789.ko decompile — exceeding any of
# these panics via __gpufreq_abort, there is nothing to "bypass"):
# - regulator_set_voltage max 0x13BB45 uV -> table units <= 129696
# - freq_scale fallback ladder rejects > 1900000; the table-hit path has no
#   clamp but the PLL-lock readback aborts on mismatch, so raise fmax gradually
import sys

RATIO = 682  # V = F_MHz * 0.682 (x1000 for integer math)
PMIC_GRID = 625
V_MAX = 129696  # 0x13BB45 uV regulator ceiling / 10
F_STEP = 50000
F_MERGE = 1100000

# tail idx3..44: freq, volt, vsram, posdiv, margin (live-UV, from unit, OK)
TAIL = [
 (1058000,75000,76250,1,1875),(1045000,74375,75625,1,1875),
 (1031000,73750,75000,1,1875),(1017000,73125,75000,1,1875),
 (1003000,72500,75000,1,1875),(990000,71875,75000,1,1875),
 (976000,71250,75000,1,1875),(962000,71250,75000,1,1875),
 (948000,70625,75000,2,1875),(935000,70000,75000,2,1875),
 (921000,69375,75000,2,1875),(907000,68750,75000,2,1875),
 (893000,68125,75000,2,1875),(880000,67500,75000,2,1875),
 (868000,66875,75000,2,1875),(857000,66875,75000,2,1875),
 (846000,66250,75000,2,1875),(835000,65625,75000,2,1250),
 (823000,65000,75000,2,1250),(812000,65000,75000,2,1250),
 (801000,64375,75000,2,1250),(790000,63750,75000,2,1250),
 (778000,63750,75000,2,1250),(767000,63125,75000,2,1250),
 (756000,62500,75000,2,1250),(745000,61875,75000,2,1250),
 (733000,61875,75000,2,1250),(722000,61250,75000,2,1250),
 (711000,60625,75000,2,1250),(700000,60000,75000,2,1250),
 (674000,60000,75000,2,1250),(648000,59375,75000,2,1250),
 (622000,59375,75000,2,1250),(596000,58750,75000,2,625),
 (570000,58750,75000,2,625),(545000,58125,75000,2,625),
 (519000,58125,75000,2,625),(493000,57500,75000,2,625),
 (467000,57500,75000,2,625),(441000,56875,75000,2,625),
 (415000,56875,75000,2,625),(390000,56250,75000,2,625),
]

def snap(v):
    return (v + PMIC_GRID // 2) // PMIC_GRID * PMIC_GRID

def volt_raw(f):
    return (f * RATIO + 5000) // 10000

def main():
    fmax = int(sys.argv[1]) * 1000
    assert 1200000 <= fmax <= 1900000 and fmax % 50000 == 0, "variants 1200-1900 step 50"
    delta = 0
    if len(sys.argv) > 2:  # UV/OV step: shift the whole curve, keep its shape
        delta = snap(int(sys.argv[2])) - snap(volt_raw(fmax))
    v0 = snap(volt_raw(fmax) + delta)
    head = []
    f = fmax
    while f >= F_MERGE:
        v = snap(volt_raw(f) + delta)
        s = v if v > 75000 else 75000  # sram retention floor, same as module tail
        head.append((f, v, s, 1, 1875))
        f -= F_STEP
    tbl = head + TAIL[len(head) - 3:]
    assert len(tbl) == 45, f"entry count {len(tbl)} != 45"
    # guard = largest step in the table + 5000 slack (live tail can drift with AVS
    # from the TAIL snapshot; the module validates the live-merged result, not the snapshot)
    maxstep = max(abs(tbl[i][1] - tbl[i - 1][1]) for i in range(1, len(tbl)))
    V_GUARD = maxstep + 5000
    for i, (f, v, s, p, m) in enumerate(tbl):
        assert 187500 <= f <= 1900000, f"freq idx{i} {f}"
        assert 50000 <= v <= V_MAX, f"volt idx{i} {v}"
        assert 75000 <= s <= V_MAX, f"vsram idx{i} {s}"
        if i:
            pf, pv = tbl[i-1][0], tbl[i-1][1]
            assert f < pf, f"freq idx{i} not descending"
            assert abs(v - pv) <= V_GUARD, f"volt step idx{i} {abs(v-pv)}"
    print(f"// generated by gen_opp.py, variant {fmax//1000}MHz @{v0}uV "
          f"(F*0.682 snapped 625) + live-UV tail. power=0 (computed by module).")
    print(f"#define HEAD_NUM {len(head)}")
    print(f"#define HEAD_VGUARD {V_GUARD}")
    print("static struct opp opp_new[OPP_NUM] = {")
    for f, v, s, p, m in tbl:
        print(f"  {{{f},{v},{s},{p},{m},0}},")
    print("};")
    print(f"// idx0 {fmax} {v0} | entries {len(tbl)} | OK",
          file=sys.stderr)

main()
