// MT6789 GPU UV+OC via working-table patch (option B).
// Variants 1200-1700MHz (gen_opp.py), UV -1250 mid-stack.
// Method: modify existing entries, OPP_NUM stays 45. No hot-path hooks.
// Call the wrapper's official getters, patch on init (GPU idle), restore on exit.
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/errno.h>
#include <linux/string.h>

#define OPP_NUM 45
#define ENTRY_U32 6
#define UV_OFFSET 1250 // -12.5mV mid-stack, hardcoded (no module_param)

// Official getters from mtk_gpufreq_wrapper_legacy.ko (EXPORT_SYMBOL, no crc
// under GKI basic-modversions so version-independent). type 1 = GPU.
extern void *gpufreq_get_working_table(unsigned int type);
extern unsigned int gpufreq_get_opp_num(unsigned int type);

struct opp { u32 freq, volt, vsram, posdiv, margin, power; };

// Per-variant 45-entry OPP table, generated by tools/gen_opp.py -> src/opp_table.h:
// 50MHz/1875uV staircase from Fmax down to 1100, live-UV tail below.
// power is ignored here (recomputed via dyn_power at init).
#include "opp_table.h"

static struct opp opp_backup[OPP_NUM];
static void *tbl_addr;
static bool patched;

static bool uvoc_in_range(u32 f, u32 v, u32 s)
{
  if (f < 187500 || f > 1900000)
    return false;
  if (v < 50000 || v > 129300)
    return false;
  if (s < 75000 || s > 129300)
    return false;
  return true;
}

static u32 dyn_power(u32 f, u32 v)
{
  u64 a = (u64)f * 100 / 1100000;
  u64 b = (u64)v * 100 / 85000;
  return (u32)(a * b * b * 0x3d1 / 1000000);
}

static int __init uvoc_init(void)
{
  u32 *t;
  unsigned int n;
  int i;

  n = gpufreq_get_opp_num(1);
  if (n != OPP_NUM) {
    pr_err("[gpu-uvoc] OPP_NUM=%u, expected 45, abort (PRI: segment/AVS mismatch)\n", n);
    return -EINVAL;
  }
  t = (u32 *)gpufreq_get_working_table(1);
  if (!t) {
    pr_err("[gpu-uvoc] working table null\n");
    return -ENOENT;
  }
  tbl_addr = t;
  for (i = 0; i < OPP_NUM; i++) { // manual backup, avoid importing memcpy
    int j;
    for (j = 0; j < ENTRY_U32; j++)
      ((u32 *)opp_backup)[i * ENTRY_U32 + j] = t[i * ENTRY_U32 + j];
  }

  // build idx HEAD_NUM+ from the live table - UV_OFFSET (follows AVS/aging).
  // idx <HEAD_NUM = fixed staircase (no live reference above 1100).
  for (i = HEAD_NUM; i < OPP_NUM; i++) {
    u32 f = t[i * ENTRY_U32 + 0];
    u32 v = t[i * ENTRY_U32 + 1];
    u32 s = t[i * ENTRY_U32 + 2];
    u32 nv = (v > (u32)UV_OFFSET) ? v - UV_OFFSET : v;
    u32 ns = (s > 75000 + (u32)UV_OFFSET) ? s - UV_OFFSET : s;
    if (nv < 50000)
      nv = 50000;
    if (ns < 75000)
      ns = 75000;
    opp_new[i].freq = f;
    opp_new[i].volt = nv;
    opp_new[i].vsram = ns;
    opp_new[i].posdiv = t[i * ENTRY_U32 + 3];
    opp_new[i].margin = t[i * ENTRY_U32 + 4];
    opp_new[i].power = dyn_power(f, nv);
  }
  opp_new[0].power = dyn_power(opp_new[0].freq, opp_new[0].volt);
  opp_new[1].power = dyn_power(opp_new[1].freq, opp_new[1].volt);
  opp_new[2].power = dyn_power(opp_new[2].freq, opp_new[2].volt);

  for (i = 0; i < OPP_NUM; i++) {
    if (!uvoc_in_range(opp_new[i].freq, opp_new[i].volt, opp_new[i].vsram)) {
      pr_err("[gpu-uvoc] entry %d out of range f=%u v=%u s=%u, abort\n",
             i, opp_new[i].freq, opp_new[i].volt, opp_new[i].vsram);
      return -EINVAL;
    }
    if (abs((int)opp_new[i].volt - (int)opp_new[(i > 0) ? i - 1 : 0].volt) > HEAD_VGUARD && i > 0) {
      pr_err("[gpu-uvoc] volt step idx%d >%d, abort\n", i, HEAD_VGUARD);
      return -EINVAL;
    }
  }

  // apply: 6 u32 per entry. posdiv/margin follow the header (staircase posdiv 1,
  // tail = live values, so no-op below). Small race window; patch while idle.
  for (i = 0; i < OPP_NUM; i++) {
    t[i * ENTRY_U32 + 0] = opp_new[i].freq;
    t[i * ENTRY_U32 + 1] = opp_new[i].volt;
    t[i * ENTRY_U32 + 2] = opp_new[i].vsram;
    t[i * ENTRY_U32 + 3] = opp_new[i].posdiv;
    t[i * ENTRY_U32 + 4] = opp_new[i].margin;
    t[i * ENTRY_U32 + 5] = opp_new[i].power;
  }
  patched = true;
  pr_info("[gpu-uvoc] patched: idx0 %u/%u idx1 %u/%u, UV -%d mid-stack\n",
          opp_new[0].freq, opp_new[0].volt, opp_new[1].freq, opp_new[1].volt, UV_OFFSET);
  pr_info("[gpu-uvoc] verify: cat /proc/gpufreqv2/gpu_working_opp_table; echo 0 > .../fix_target_opp_index for max-lock test\n");
  return 0;
}

static void __exit uvoc_exit(void)
{
  int i;
  if (patched && tbl_addr) {
    u32 *t = (u32 *)tbl_addr; // manual restore
    for (i = 0; i < OPP_NUM; i++) {
      int j;
      for (j = 0; j < ENTRY_U32; j++)
        t[i * ENTRY_U32 + j] = ((u32 *)opp_backup)[i * ENTRY_U32 + j];
    }
    pr_info("[gpu-uvoc] working table restored\n");
  }
}

module_init(uvoc_init);
module_exit(uvoc_exit);
MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("MT6789 GPU UV(-12.5mV)+OC working-table patch, variant via opp_table.h");

